# GoReleaser configuration for webdav-115drive
# Documentation: https://goreleaser.com

version: 2

# Project metadata
project_name: webdav-115drive

# Build configuration
builds:
  - id: webdav-115drive
    main: .
    binary: webdav-115drive

    # Multi-platform builds
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
    env:
      - CGO_ENABLED=0

# Archive configuration
archives:
  - id: default
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Tag }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md
      - LICENSE
      - config.yaml.example
      - .env.example

# Checksums
checksum:
  name_template: '{{ .ProjectName }}_{{ .Tag }}_checksums.txt'
  algorithm: sha256

# Changelog generation using GitHub's native release notes API
# This generates "What's Changed" automatically with contributor info
changelog:
  use: github-native

# Docker image configuration (v2)
dockers_v2:
  - id: webdav-115drive
    dockerfile: Dockerfile.goreleaser
    platforms:
      - linux/amd64
      - linux/arm64
    images:
      - "heartleo/webdav-115drive"
      - "ghcr.io/heartleo/webdav-115drive"
    tags:
      - "{{ .Tag }}"
      - "{{ if not .Prerelease }}latest{{ end }}"
    # Disable SBOM and provenance to avoid unknown/unknown platform in manifest
    sbom: false
    flags:
      - "--provenance=false"
    labels:
      org.opencontainers.image.title: "{{ .ProjectName }}"
      org.opencontainers.image.description: "A WebDAV service for 115drive"
      org.opencontainers.image.url: "https://github.com/heartleo/webdav-115drive"
      org.opencontainers.image.source: "https://github.com/heartleo/webdav-115drive"
      org.opencontainers.image.version: "{{ .Tag }}"
      org.opencontainers.image.created: "{{ .Date }}"
      org.opencontainers.image.revision: "{{ .FullCommit }}"
      org.opencontainers.image.licenses: "MIT"

# GitHub Release configuration
release:
  github:
    owner: heartleo
    name: webdav-115drive

  # Automatically detect prerelease versions (containing -alpha, -beta, -rc, etc.)
  prerelease: auto

  # Release name format (use tag name directly)
  name_template: "{{.Tag}}"

  # Draft release for manual review before publishing
  # Set to true to create draft releases that need manual publishing
  draft: true

  # Release footer
  footer: |
    ## Installation

    ### Binary
    Download the appropriate binary for your platform from the assets below.

    ### Docker
    ```bash
    docker pull heartleo/webdav-115drive:{{ .Tag }}
    # or
    docker pull ghcr.io/heartleo/webdav-115drive:{{ .Tag }}
    ```