name: 🚀 Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please provide as much detail as possible.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: |
        I'm frustrated when...
        It would be helpful if...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: |
        I would like webdav-115drive to...
        This could work by...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe alternatives you've considered
      placeholder: |
        Alternative 1: ...
        Alternative 2: ...
    validations:
      required: false

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New WebDAV functionality
        - Performance improvement
        - Configuration option
        - API/Integration
        - CLI improvement
        - Docker/Deployment
        - Security enhancement
        - Other
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your use case for this feature
      placeholder: |
        I need this feature because...
        It will help me to...
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples
      placeholder: Links to similar implementations, screenshots, code examples, etc.
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Checks
      description: Please confirm the following
      options:
        - label: I have searched existing issues and discussions for similar proposals
          required: true
        - label: This feature aligns with the project's goals (WebDAV proxy for 115 Drive)
          required: true
        - label: I am willing to help implement this feature if guidance is provided
          required: false
